version: '3.8'

# Lyra Discord Bot - Docker Compose Configuration
# The Docker build uses npm instead of yarn for better container compatibility

services:
  lyra-bot:
    build: .
    container_name: lyra-discord-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OWNERS=${OWNERS}
      - SQLITE_PATH=/app/data/word_triggers.db
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
    networks:
      - lyra-network

networks:
  lyra-network:
    driver: bridge

volumes:
  lyra-data: