version: '3.9'

services:
  postgres:
    container_name: postgres
    image: 'postgres:17-alpine'
    networks:
      = infi
    restart: always
    volumes:
      = 'postgres-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    logging:
      options:
        max-size: '20m'
        max-file: '3'

  lyra:
    build:
      context: ../
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    env_file:
      - ../src/.env
      - ../src/.env.local
    container_name: lyra
    logging:
      options:
        max-size: '1g'
        max-file: '3'
    networks:
      - infi
    restart: always
    tty: true
    image: lyra:latest

volumes:
  postgres-data:
    external: true

networks:
  inf: