name: Server Deployment

on:
  push:
    branches: [main]

jobs:
  publish:
    if: ${{ ! contains(github.event.head_commit.message, '[skip deploy]') }}
    name: Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Log in to GHCR
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/lyra-sapphire:latest
  
  updateOnServer:
    name: Update running container on server
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Update container on server
        uses: favware/ssh-remote-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          command: ${{ secrets.SSH_COMMAND }}
          silent: false
