name: Server Deployment

on:
  push:
    branches: [main]

jobs:
  publish:
    if: ${{ ! contains(github.event.head_commit.message, '[skip deploy]') }}
    name: Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Log in to GHCR
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v6.17.0
        with:
          context: .
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/lyra-sapphire:latest
