name: Lint code

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: yarn i
        run: yarn install

      - name: Prettify code
        run: |
            yarn format

      - name: Push changes
        run: |
            if ! git diff-index --quiet HEAD --; then 
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add .
              git commit -m "chore: Lint Code"
              git push
            fi
