name: Prettier-Lint

# This action works with pull requests and pushes
on:
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Prettify code
        run: |
            yarn format

      - name: Compare output
        run: |
            if ! git diff-index --quiet HEAD --; then 
              echo "This code is not linted properly. Marking job as failed..."
              exit 1
            fi
